# Generated by Django 3.0.8 on 2020-08-03 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='گروه بورسی', max_length=120, null=True)),
                ('createAt', models.DateField(default=django.utils.timezone.now, help_text='تاریخ ایجاد')),
                ('pic', models.ImageField(blank=True, help_text='تصویر', null=True, upload_to='', verbose_name='uploaded image')),
                ('description', models.TextField(blank=True, help_text='توضیحات', max_length=10000, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='کاربر', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['createAt'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, help_text='نماد', max_length=120, null=True)),
                ('fullName', models.CharField(blank=True, help_text='نام شرکت', max_length=120, null=True)),
                ('alias', models.CharField(blank=True, help_text='نام معادل انگلیسی', max_length=120, null=True)),
                ('type', models.CharField(choices=[('0', 'شاخص کل'), ('1', 'نماد'), ('2', 'شاخص صنعت')], default='1', help_text='نوع نماد', max_length=20)),
                ('bourseType', models.CharField(blank=True, help_text='بازار بورس', max_length=120, null=True)),
                ('pic', models.ImageField(blank=True, help_text='تصویر', null=True, upload_to='', verbose_name='uploaded image')),
                ('createAt', models.DateField(default=django.utils.timezone.now, help_text='تاریخ ایجاد')),
                ('tse', models.URLField(blank=True, help_text='لینک tse', null=True)),
                ('site', models.URLField(blank=True, help_text='وبسایت', null=True)),
                ('isTarget', models.BooleanField(default=False, help_text='تحت نظر')),
                ('isSuperUserPermition', models.BooleanField(default=False, help_text='دسترسی سطح بالا')),
                ('hit_count', models.BigIntegerField(default=0)),
                ('description', models.TextField(blank=True, help_text='توضیحات', max_length=10000, null=True)),
                ('category', models.ForeignKey(blank=True, help_text='گروه', null=True, on_delete=django.db.models.deletion.CASCADE, to='bourse.Category')),
                ('user', models.ForeignKey(blank=True, help_text='کاربر', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['createAt'],
            },
        ),
        migrations.CreateModel(
            name='Watcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocks', models.TextField(help_text='نام سهم ها')),
                ('user_id', models.ForeignKey(help_text='کاربر', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='ممنوع،متوقف', help_text='وضعیت نماد', max_length=250)),
                ('trade_volume', models.BigIntegerField(default=0, help_text='حجم معاملات')),
                ('stock_price_max', models.IntegerField(default=0, help_text='بیشترین قیمت سهم')),
                ('stock_price_min', models.IntegerField(default=0, help_text='کمترین قیمت سهم')),
                ('latest_price', models.IntegerField(default=0, help_text='آخرین قیمت')),
                ('latest_price_indicator_effect', models.IntegerField(default=0, help_text='تاثیر آخرین قیمت بر شاخص', null=0)),
                ('latest_price_indicator_effect_percent', models.IntegerField(default=0, help_text='درصد تاثیر آخرین قیمت بر شاخص', null=0)),
                ('final_price', models.IntegerField(default=0, help_text='قیمت پایانی', null=0)),
                ('final_price_indicator_effect', models.IntegerField(default=0, help_text='تاثیر قیمت پایانی بر شاخص', null=0)),
                ('final_price_indicator_effect_percent', models.IntegerField(default=0, help_text='درصد تاثیر قیمت پایانی بر شاخص', null=0)),
                ('symbol', models.ForeignKey(help_text='نماد', on_delete=django.db.models.deletion.CASCADE, to='bourse.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.BigIntegerField()),
                ('date', models.DateTimeField()),
                ('action', models.CharField(default='Buy', max_length=100)),
                ('volume', models.IntegerField(help_text='حجم')),
                ('price', models.IntegerField(help_text='قیمت')),
                ('done', models.IntegerField(help_text='حجم انجام شده')),
                ('status', models.BooleanField(default=0, help_text='وضعیت')),
                ('account_type', models.CharField(default='حساب نزد کارگزار', help_text='نوع حساب', max_length=150)),
                ('source', models.CharField(default='وب سایت', help_text='مبدأ', max_length=150)),
                ('symbol', models.ForeignKey(help_text='نماد', on_delete=django.db.models.deletion.CASCADE, to='bourse.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_balance', models.IntegerField(default=0, help_text='دارایی سهم')),
                ('selling_value', models.IntegerField(default=0, help_text='ارزش فروش')),
                ('neutral_price', models.IntegerField(default=0, help_text='قیمت سر به سر')),
                ('latest_price', models.IntegerField(default=0, help_text='آخرین قیمت')),
                ('final_price', models.IntegerField(default=0, help_text='قیمت پایانی', null=0)),
                ('today_sell', models.IntegerField(default=0, help_text='فروش امروز', null=0)),
                ('today_buy', models.IntegerField(default=0, help_text='خرید امروز', null=0)),
                ('open_order', models.IntegerField(default=0, help_text='سفارشات باز', null=0)),
                ('owner', models.ForeignKey(help_text='کاربر', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('symbol', models.ForeignKey(help_text='نماد', on_delete=django.db.models.deletion.CASCADE, to='bourse.Company')),
            ],
        ),
    ]
